# Generated by Django 2.2 on 2019-09-09 12:07

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.FileField(blank=True, upload_to='paket_umroh/%Y/%m/%d')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('fasilitas', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Tiket Pesawat PP'), (2, 'Hotel Madinah & Makkah, Makan 3x sehari'), (3, 'Transportasi Bus Full AC'), (4, 'Manasik Umroh Teori dan Praktik'), (5, 'Tour Leader & Mutawwif Profesional'), (6, 'City Tour Sesuai Program'), (7, 'Airport Handling'), (8, 'Air Zam-Zam'), (9, 'Perlengkapan Umroh Standar (Kain Ihram (pria), Mukena (wanita), Baju Seragam, Tas Troley/Koper, Hand Bag, Buku Manasik; label bagasi dll)'), (10, 'Biaya kelebihan bagasi (max 25 kg/orang)'), (11, 'Biaya pembuatan paspor dengan 3 suku kata'), (12, 'Biaya suntik meningitis dan atau flu'), (13, 'Pembuatan surat mahram (bagi yang memerlukan mahram)'), (14, 'Airport Tax Handling'), (15, 'Pengeluaran pribadi : kelebihan bagasi (max 25 kg/orang), telepon, laundry dll')], max_length=35)),
                ('populer', models.BooleanField(default=False)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perjalanan', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'A Saha - Madinah'), (2, 'Bahauddin - Madinah'), (3, 'Al Haram - Madinah'), (4, 'Ajyad Makarem - Makkah'), (5, 'Le Meriddien - Makkah'), (6, 'Dar Al Leman - Makkah')], max_length=11)),
                ('pesawat', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Etihad'), (2, 'Saudi Arabia'), (3, 'Emirates'), (4, 'Turish Airlines')], max_length=7)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package')),
            ],
        ),
    ]
