# Generated by Django 2.2 on 2019-09-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='fasilitas',
            field=models.ManyToManyField(blank=True, help_text='Tekan item fasilitas, untuk memilih lebih dari satu', to='packages.Facility'),
        ),
    ]
