# Generated by Django 2.2 on 2019-09-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20190916_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='fasilitas',
            field=models.ManyToManyField(blank=True, to='packages.Facility'),
        ),
    ]
