# Generated by Django 2.2 on 2019-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20190916_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='fasilitas',
            field=models.ManyToManyField(blank=True, help_text=None, to='packages.Facility'),
        ),
    ]
