# Generated by Django 2.2 on 2019-09-16 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20190916_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='penulis'),
        ),
        migrations.AlterField(
            model_name='package',
            name='fasilitas',
            field=models.ManyToManyField(blank=True, to='packages.Facility'),
        ),
        migrations.AlterField(
            model_name='package',
            name='label',
            field=models.CharField(blank=True, choices=[('populer', 'POPULER'), ('promo', 'PROMO'), (None, '--normal--')], help_text='optional', max_length=7),
        ),
    ]
