# Generated by Django 2.2 on 2019-09-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20190916_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=225)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'package hotel',
                'ordering': ('nama',),
            },
        ),
        migrations.AlterModelOptions(
            name='airline',
            options={'ordering': ('nama',), 'verbose_name_plural': 'package airlines'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='maskapai',
            new_name='nama',
        ),
        migrations.AlterField(
            model_name='package',
            name='label',
            field=models.CharField(blank=True, choices=[('populer', 'POPULER'), ('promo', 'PROMO'), (None, '--normal--')], help_text='Optional', max_length=7),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('berangkat', 'Berangkat'), ('kembali', 'Kembali'), (None, 'Unknown')], help_text='Optional', max_length=9)),
                ('tanggal', models.DateField(blank=True, help_text='Optional', null=True)),
                ('maskapai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.Airline')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package')),
            ],
            options={
                'verbose_name_plural': ('package flights',),
                'ordering': ('paket',),
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai_tanggal', models.DateField(blank=True, null=True)),
                ('akhir_tanggal', models.DateField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Hotel')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package')),
            ],
            options={
                'verbose_name_plural': 'package accomodations',
                'ordering': ('paket',),
            },
        ),
        migrations.AddField(
            model_name='package',
            name='akomodasi',
            field=models.ManyToManyField(blank=True, through='packages.Accommodation', to='packages.Hotel'),
        ),
        migrations.AddField(
            model_name='package',
            name='penerbangan',
            field=models.ManyToManyField(blank=True, through='packages.Flight', to='packages.Airline'),
        ),
    ]
