# Generated by Django 2.2 on 2019-09-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20190916_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ('paket',), 'verbose_name_plural': 'package flights'},
        ),
    ]
