# Generated by Django 2.2 on 2019-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20190916_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='akhir_tanggal',
            field=models.DateField(blank=True, help_text='Tanggal akhir penginapan. Optional', null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='mulai_tanggal',
            field=models.DateField(blank=True, help_text='Tanggal mulai penginapan. Optional', null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('berangkat', 'Berangkat'), ('kembali', 'Kembali'), (None, 'Unknown')], help_text='Status penerbangan berangkat / kembali. Optional', max_length=9),
        ),
        migrations.AlterField(
            model_name='flight',
            name='tanggal',
            field=models.DateField(blank=True, help_text='Tanggal penerbangan. Optional', null=True),
        ),
    ]
