# Generated by Django 2.2 on 2019-09-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20190916_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(blank=True, choices=[('berangkat', 'Berangkat'), ('kembali', 'Kembali'), (None, 'Unknown')], help_text='Status penerbangan berangkat / kembali. Optional', max_length=9, null=True),
        ),
    ]
