# Generated by Django 2.2 on 2019-09-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_auto_20190916_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(blank=True, choices=[('berangkat', 'Berangkat'), ('kembali', 'Kembali')], help_text='Status penerbangan berangkat / kembali. Optional', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='label',
            field=models.CharField(blank=True, choices=[('populer', 'POPULER'), ('promo', 'PROMO')], help_text='Optional', max_length=7),
        ),
    ]
