# Generated by Django 2.2 on 2019-09-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_auto_20190916_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perjalanan', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, upload_to='package/traveldetail/img')),
                ('deskripsi', models.TextField(blank=True)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
