# Generated by Django 2.2 on 2019-09-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
