# Generated by Django 2.2 on 2019-09-16 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_hotel_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AirlineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='package/airline/img/')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Airline')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
