# Generated by Django 2.2 on 2019-09-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_auto_20190917_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='deskripsi',
            field=models.TextField(blank=True, help_text='Deskripsi airline / maskapai. Optional', null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='deskripsi',
            field=models.TextField(blank=True, help_text='Deskripsi hotel. Optional', null=True),
        ),
    ]
