# Generated by Django 2.2 on 2019-09-09 12:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('kategori', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Kategori 1'), (2, 'Kategori 2')], default=1, max_length=3)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
