# Generated by Django 2.2 on 2019-09-25 03:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='judul', unique=True),
        ),
    ]
