# Generated by Django 2.2 on 2019-09-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('visi_misi', models.TextField(blank=True, null=True, verbose_name='Visi & Misi')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Us',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, help_text='Biaya perjalanan termasuk/tidak-termasuk.', max_length=225, null=True)),
                ('status', models.CharField(choices=[('termasuk', 'Termasuk'), ('tidaktermasuk', 'Tidak Termasuk')], max_length=14)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abouts.About')),
            ],
            options={
                'verbose_name_plural': 'services',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PhotosActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, help_text='Foto Kegiatan.', null=True, upload_to='about_us/photos_of_activities')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abouts.About')),
            ],
            options={
                'verbose_name_plural': 'photos of activities',
                'ordering': ('id',),
            },
        ),
    ]
