# Generated by Django 2.2 on 2019-09-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='home',
        ),
    ]
